from db_connect import Base
from models.category import Categories
from models.laptop import Laptops
from models.planshet import Planshets
from models.telephone import Telephones
from models.user import Users
from models.buy import Buys
from models.cart import Carts
from models.incomit import Incomes
from models.like import Likes
from models.file import Files
